print("=== CADASTRO DE CLIENTE ===")

nome = input("Nome: ")
cpf = input("CPF: ").replace(".", "").replace("-", "")
telefone = input("Telefone: ")
email = input("Email: ")
endereco = input("Endereço: ")
data_cadastro = input("Data de cadastro (DD/MM/AAAA): ")

print("\n=== DADOS CADASTRADOS ===")
print(f"Nome: {nome}")
print(f"CPF: {cpf}")
print(f"Telefone: {telefone}")
print(f"Email: {email}")
print(f"Endereço: {endereco}")
print(f"Data de cadastro: {data_cadastro}")
